const STORAGE_KEY="jv-catalog-admin-draft-v1";
const PAGE_SIZE=30;
const state={projects:[],filtered:[],draft:{},selected:new Set(),page:1,query:"",status:"",category:"",authenticated:false};
const $=(selector)=>document.querySelector(selector);
const rows=$("#projectRows"),search=$("#adminSearch"),statusFilter=$("#statusFilter"),categoryFilter=$("#categoryFilter");
function projectStatus(p){return p.status||"published"}
function merged(project){return {...project,...(state.draft[project.repoName]||{})}}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function sourceLabel(p){if(p.sourceGroup==="ai-case")return "AI 產業案例";if(p.sourceGroup==="smart-manufacturing")return "智慧製造";return "JV 整合專案"}
function statusLabel(value){return ({published:"公開展示",draft:"草稿",archived:"封存"})[value]||value}
function loadDraft(){try{state.draft=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")||{}}catch{state.draft={}}}
function persistDraft(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.draft));updateStats()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600)}
function updateStats(){const all=state.projects.map(merged);$("#totalStat").textContent=all.length;$("#publishedStat").textContent=all.filter(p=>projectStatus(p)==="published").length;$("#featuredStat").textContent=all.filter(p=>p.featured).length;const count=Object.keys(state.draft).length;$("#changedStat").textContent=count;$("#draftCount").textContent=count}
function applyFilters(){const q=search.value.trim().toLowerCase();state.query=q;state.status=statusFilter.value;state.category=categoryFilter.value;state.filtered=state.projects.map(merged).filter(p=>(!q||[p.id,p.title,p.repoName,p.category,p.industry].join(" ").toLowerCase().includes(q))&&(!state.status||projectStatus(p)===state.status)&&(!state.category||p.category===state.category));state.page=1;render()}
function render(){const pages=Math.max(1,Math.ceil(state.filtered.length/PAGE_SIZE));state.page=Math.min(state.page,pages);const slice=state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE);rows.innerHTML=slice.map(p=>`<tr><td><input type="checkbox" data-select="${escapeHtml(p.repoName)}" ${state.selected.has(p.repoName)?"checked":""} aria-label="選取 ${escapeHtml(p.title)}"></td><td class="project-cell"><b>${escapeHtml(p.title||p.repoName)}</b><small>#${escapeHtml(p.id)} · ${escapeHtml(p.repoName)}</small></td><td>${escapeHtml(p.category||"未分類")}</td><td>${escapeHtml(sourceLabel(p))}</td><td><span class="status status-${projectStatus(p)}">${statusLabel(projectStatus(p))}</span></td><td>${p.featured?'<span class="featured">精選</span>':'—'}</td><td>${state.draft[p.repoName]?"草稿已修改":"尚未修改"}</td><td><div class="row-actions"><button type="button" data-edit="${escapeHtml(p.repoName)}">編輯</button><a href="${escapeHtml(p.demoUrl||'#')}" target="_blank" rel="noreferrer">預覽</a></div></td></tr>`).join("");$("#tableSummary").textContent=`符合 ${state.filtered.length} 個專案，目前顯示第 ${state.page} 頁`;$("#pageLabel").textContent=`${state.page} / ${pages}`;$("#prevPage").disabled=state.page<=1;$("#nextPage").disabled=state.page>=pages;updateBulkBar()}
function updateBulkBar(){const n=state.selected.size;$("#bulkBar").hidden=n===0;$("#selectedCount").textContent=n}
function editProject(repo){const p=merged(state.projects.find(x=>x.repoName===repo));if(!p)return;$("#editRepo").value=repo;$("#editTitle").value=p.title||"";$("#editCategory").value=p.category||"";$("#editIndustry").value=p.industry||"";$("#editStatus").value=projectStatus(p);$("#editFeatured").checked=Boolean(p.featured);$("#editTags").value=(p.tags||[]).join(", ");$("#editNotes").value=p.notes||"";$("#editorDialog").showModal()}
function saveEditor(event){event.preventDefault();const repo=$("#editRepo").value;state.draft[repo]={title:$("#editTitle").value.trim(),category:$("#editCategory").value.trim(),industry:$("#editIndustry").value.trim(),status:$("#editStatus").value,featured:$("#editFeatured").checked,tags:$("#editTags").value.split(",").map(x=>x.trim()).filter(Boolean),notes:$("#editNotes").value.trim()};persistDraft();$("#editorDialog").close();applyFilters();toast("專案變更已儲存至本機草稿")}
function renderChanges(){const entries=Object.entries(state.draft);$("#changesList").innerHTML=entries.length?entries.map(([repo,change])=>{const base=state.projects.find(p=>p.repoName===repo)||{};const fields=Object.keys(change).filter(k=>JSON.stringify(change[k])!==JSON.stringify(base[k]??(k==="status"?"published":k==="featured"?false:k==="tags"?[]:"")));return `<article class="change-item"><div><b>${escapeHtml(change.title||base.title||repo)}</b><small>${escapeHtml(repo)} · ${fields.map(x=>({title:"名稱",category:"分類",industry:"說明",status:"狀態",featured:"精選",tags:"標籤",notes:"備註"})[x]).join("、")}</small></div><button type="button" data-remove-change="${escapeHtml(repo)}">移除</button></article>`}).join(""):'<p>目前沒有尚未送出的變更。</p>';$("#confirmSubmit").disabled=!entries.length;$("#changesDialog").showModal()}
async function login(event){event.preventDefault();const error=$("#loginError");error.textContent="";const button=event.submitter;button.disabled=true;try{const response=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:$("#adminPassword").value})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"登入失敗")};state.authenticated=true;$("#loginDialog").close();toast("已登入管理中心")}catch(e){error.textContent=e.message}finally{button.disabled=false}}
async function checkSession(){try{const response=await fetch("/api/admin/session");state.authenticated=response.ok}catch{state.authenticated=false}$("#logoutButton").textContent=state.authenticated?"登出":"登入"}
async function submitChanges(){if(!state.authenticated){$("#changesDialog").close();$("#loginDialog").showModal();return}const button=$("#confirmSubmit");button.disabled=true;button.textContent="建立中…";try{const response=await fetch("/api/admin/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({changes:state.draft})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"無法建立變更提案");localStorage.removeItem(STORAGE_KEY);state.draft={};$("#changesDialog").close();applyFilters();toast("GitHub 變更 PR 已建立");if(data.prUrl)window.open(data.prUrl,"_blank","noopener")}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent="建立 GitHub PR"}}
async function boot(){loadDraft();const response=await fetch("./projects-index.json");const data=await response.json();state.projects=data.projects;state.filtered=state.projects.map(merged);[...new Set(state.projects.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"zh-Hant")).forEach(value=>categoryFilter.add(new Option(value,value)));updateStats();render();checkSession()}
search.addEventListener("input",applyFilters);statusFilter.addEventListener("change",applyFilters);categoryFilter.addEventListener("change",applyFilters);rows.addEventListener("click",event=>{const edit=event.target.closest("[data-edit]");if(edit)editProject(edit.dataset.edit)});rows.addEventListener("change",event=>{const box=event.target.closest("[data-select]");if(!box)return;box.checked?state.selected.add(box.dataset.select):state.selected.delete(box.dataset.select);updateBulkBar()});$("#editorForm").addEventListener("submit",saveEditor);$("#prevPage").onclick=()=>{state.page--;render()};$("#nextPage").onclick=()=>{state.page++;render()};$("#selectPage").onchange=event=>{state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE).forEach(p=>event.target.checked?state.selected.add(p.repoName):state.selected.delete(p.repoName));render()};$("#clearSelection").onclick=()=>{state.selected.clear();render()};$("#bulkStatus").onchange=event=>{if(!event.target.value)return;state.selected.forEach(repo=>state.draft[repo]={...state.draft[repo],status:event.target.value});event.target.value="";persistDraft();applyFilters();toast("已套用批次狀態")};$("#bulkFeatured").onclick=()=>{state.selected.forEach(repo=>{const p=merged(state.projects.find(x=>x.repoName===repo));state.draft[repo]={...state.draft[repo],featured:!p.featured}});persistDraft();applyFilters();toast("已切換精選狀態")};$("#openChanges").onclick=renderChanges;$("#submitChanges").onclick=renderChanges;$("#changesList").onclick=event=>{const b=event.target.closest("[data-remove-change]");if(!b)return;delete state.draft[b.dataset.removeChange];persistDraft();renderChanges();applyFilters()};document.querySelectorAll("[data-close-dialog]").forEach(b=>b.onclick=()=>$("#"+b.dataset.closeDialog).close());$("#confirmSubmit").onclick=submitChanges;$("#discardDraft").onclick=()=>{if(!Object.keys(state.draft).length)return;if(confirm("確定清除所有尚未送出的變更草稿？")){state.draft={};persistDraft();applyFilters();toast("草稿已清除")}};$("#loginForm").addEventListener("submit",login);$("#logoutButton").onclick=async()=>{if(!state.authenticated){$("#loginDialog").showModal();return}await fetch("/api/admin/logout",{method:"POST"});state.authenticated=false;$("#logoutButton").textContent="登入";toast("已登出管理中心")};boot().catch(()=>toast("無法載入專案目錄"));
