import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";
await mkdir("verification",{recursive:true});
const targetUrl=process.argv[2]||"http://127.0.0.1:3000";
const browser=await chromium.launch({headless:true});
const results=[];
for(const viewport of [{name:"desktop",width:1440,height:1000},{name:"mobile",width:390,height:844}]){
 const page=await browser.newPage({viewport});const errors=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});
 await page.goto(targetUrl,{waitUntil:"networkidle",timeout:30000});
 const bodyLen=(await page.locator("body").innerText()).trim().length;
 const overlay=await page.locator("[data-nextjs-dialog], .vite-error-overlay, #webpack-dev-server-client-overlay").count();
 await page.locator('a[href="#demo"]').first().click();
 await page.locator('input[aria-label="房源名稱"]').fill("測試房源 101");
 await page.locator('input[aria-label="月租金"]').fill("25000");
 await page.locator('button:has-text("新增房源")').click();
 await page.locator('article:has-text("測試房源 101") button:has-text("出租中")').click();
 await page.locator('button:has-text("產生合約並送簽")').click();
 await page.locator('input[aria-label="修繕房源"]').fill("測試房源 101");
 await page.locator('input[aria-label="修繕問題"]').fill("測試修繕建立成功");
 await page.locator('button:has-text("建立報修")').click();
 await page.locator('button:has-text("新增收款")').click();
 await page.locator('button:has-text("生成 AI 現況")').click();
 const hasUnit=await page.getByText("測試房源 101").count();
 const hasContract=await page.getByText("合約模板已產生並送簽").count();
 const hasRepair=await page.getByText("測試修繕建立成功").count();
 const hasInspection=await page.getByText("AI 現況").count();
 await page.screenshot({path:`verification/property-${viewport.name}.png`,fullPage:true});
 results.push({viewport:viewport.name,bodyLen,overlay,consoleErrors:errors,hasUnit,hasContract,hasRepair,hasInspection});
 await page.close();
}
await browser.close();
console.log(JSON.stringify(results,null,2));
